= Build Dependencies HOWTO

Before making a local build, build dependencies needs to be installed.
This document tries to describe the procedures.

== Windows

Before build, run the `buildwin\win_deps.bat` file. The file requires a
working choco installation, see
https://docs.chocolatey.org/en-us/choco/setup[https://docs.chocolatey.org/en-us/choco/setup].

The first run will install various software using choco, and should be
invoked with administrative privileges.

Subsequent builds should still invoke the file, but it can be done with
regular permissions.

A batch file has been found useful for modifying source code with Visual
Studio 2017.

== Debian/Ubuntu

Install build dependencies using something like:

....
 $ sudo apt install devscripts equivs
 $ sudo mk-build-deps -ir build-deps/control
 $ sudo apt-get -q --allow-unauthenticated install -f
....

== Flatpak

* Install flatpak and flatpak-builder as described in
https://flatpak.org/[https://flatpak.org/]
* Install the opencpn flatpak package using latest official version on
flathub:
+
....
  $ flatpak install --user flathub org.opencpn.OpenCPN
....
+
Or use the provisionary beta repo at fedorapeople.org (mirrors master):
+
....
  $ flatpak install --user \
      https://opencpn.duckdns.org/opencpn/opencpn.flatpakref
....
* The shipdriver flatpak plugin can now be built and installed using
+
....
$ cd build
$ cmake ..
$ make flatpak
....

== MacOS

Use the ci script, which just installs the build deps and configures
when used in a non-CI environment:

....
$ ci/circleci-build-macos
....

After the initial run the build dependencies are in place and
configured. Make for example the tarball using `cd build; make tarball`
