== Alternative Workflow for Managed Plugins

== Cloud Services

The following free opensource accounts/services are required:

* Deployment Repository  https://cloudsmith.io/[Cloudsmith]

* Build Tool https://circleci.com/[CircleCI]

* Build Tool https://www.appveyor.com/[Appveyor]

* Build Tool https://travis-ci.org/[Travis]

* Source Code Repository https://github.com/[GitHub]

Use the links below to see how these services are set up. Probably best
to proceed in this order to avoid retracing steps.

* 1. xref:Cloudsmith.adoc[Cloudsmith]

This entity hosts the tarballs and metadata files that form the heart of
the managed plugin system.

* 2. xref:CircleCI.adoc[CircleCI]

The purpose of the managed system is to produce installers for multiple
operating systems. CircleCI hosts virtual machines for a number of OS.

* 3. xref:Travis.adoc[Travis]

Hosts a virtual machine for the creation of installers for the Raspbian
ARMHF system.

* 4. xref:Appveyor.adoc[Appveyor]

A virtual machine for making Windows OS installers.

== The Changes

* xref:Plugin-Adaptation.adoc[Adapting the legacy plugin]

Go to this section for a description of the additional files needed to
enable the plugin to be compiled and hosted by the cloud services. Also
the changes to CMakeLists.txt for the plugin and the changes to the
source code.

* xref:GitHub.adoc[GitHub]

For this guide the plugin
https://github.com/Rasbats/TideFinder_pi[TideFinder_pi] will be used.
Some changes to the settings for the repository on GitHub are needed.

* xref:Cloud-Service-Changes.adoc[Cloud service changes]

Environment variables are added to appveyor, circleci and travis.
Changes are needed for the GitHub TideFinder and Plugins repositories.

* xref:Local-Build.adoc[Building locally]

A local build of the plug can be carried out using the tools described
on this page.

xref:index.adoc[Index]