= Local Builds

== Build Dependencies HOWTO

Before making a local build, build dependencies needs to be installed.
This document tries to describe the procedures.

When the dependencies are installed the build is done as described in
INSTALL.md which distributed in every plugin. A (possibly outdated)
copy is available in the xref:usage.adoc[Usage page].

=== Windows

Before build, run the `buildwin\win_deps.bat` file. The file requires a
working choco installation, see
https://docs.chocolatey.org/en-us/choco/setup[https://docs.chocolatey.org/en-us/choco/setup]

The first run will install various software using choco, and should be
invoked with administrative privileges.

Subsequent builds should still invoke the file, but it can be done with
regular permissions.

A batch file has been found useful for modifying source code with Visual
Studio 2017.

=== Debian/Ubuntu

If not already done, first clone the git sources. Then, in the plugin
directory, install build dependencies using something like

....
 $ sudo apt install devscripts equivs
 $ sudo mk-build-deps -ir build-deps/control
 $ sudo apt-get -q --allow-unauthenticated install -f
....

=== Flatpak

Building Flatpak requires a Linux host.  The first step is to
install flatpak as described in https://flatpak.org/setup/

Proceed by installing _flatpak-builder_. Most distributions
including Ubuntu and Fedora have this packaged, making it possible
to install using tools like _apt(8)_ or _dnf(8)_.

Then install the build dependencies using something like

    $ flatpak remote-add --user --if-not-exists \
          flathub https://flathub.org/repo/flathub.flatpakrepo
    $ flatpak install --user flathub org.freedesktop.Platform//20.08
    $ flatpak install --user flathub org.freedesktop.Sdk//20.08
    $ flatpak install --user flathub org.opencpn.OpenCPN

20.08 is the runtime version which indeed is 20.08 at the time of
writing. Review the _flatpak/org.opencpn.*yaml_ file to check this,
look for `runtime-version`.

=== Android

The templates supports creating tarballs for 32-bit armhf and 64-bit arm64 targets.
Building these requires a local installation of the Android Native Development Kid (NDK)
which can be found at https://developer.android.com/ndk/downloads[].

The build needs to locate the installed NDK. By default, it uses the path _/opt/android/ndk_.
This can be utilized by creating a symlink, something like `sudo ln -s /opt/android/android-ndk-*
/opt/android/ndk`. As an alternative, the NDK_HOME environment variable can be used.
It should contain the complete path to the NDK directory.

Android builds also needs an updated cmake version. In general, the NDK and cmake needs to be
synchronized -- an old cmake version is not likely to work with an updated NDK. This is an
issue on some platforms, notably all Debian-based which includes Ubuntu. The work-around is to
use python to install the python wheel distributed by Kitware using somehting like
`pip install --user cmake`. This requires a working, updated python3 installation.


=== MacOS

Use the ci script, which just installs the build deps and configures
when used in a non-CI environment:

....
$ ci/circleci-build-macos
....

After the initial run the build dependencies are in place and
configured. Make for example the tarball using `cd build-osx; make tarball`

== The local build environment

=== Overview

After installing build dependencies (see above) the local build environment
supports local build and deployment. The basic pieces are:

* The _local-build.rc_ configuration file. This is used by all other tools.
* The _scripts/local-build_ python script which runs complete local builds
  and deploys to cloudsmith
* The build directory. Created by the build script it is the base for
  testing and deploying the plugin.
* A build directory can also be created by a "manual" build according
  to INSTALL.md in the plugin.
* _scripts/local-upload_ which supports uploading a build directory to
  cloudsmith
* _ci/git_push_ which pushes updated metadata in a build directory to a
  clone of the plugins directory, supporting making a PR to said project
  as described in the
  xref:../InstallConfigure/Catalog-Github-Integration.adoc[github integration page]

=== The configuration file

A sample configuration file is distributed  in _scripts/local-build.rc_.
Instructions for modifying and installation is included in the sample.
Note that all other tools depends on this file.

=== Local builds.

The script _scripts/local-build_ supports building various platforms.
With complete build dependencies in place it can build native Linux,
cross-compiled Android and emulated Raspbian/armhf targets on a Linux
host. At the time of writing this is 9 builds.

On windows, the script builds a single Windows target.

Use `python scripts/local-build help` to get started. The supported targets
are listed. On Linux, all available targets can be built using `scripts/local-build
gui`. All builds includes uploading to cloudsmith, pushing metadata and
tarballs available for testing.

Local builds creates different build  directories like _build-xenial_,
_build-flatpak_ etc. in order to avoid collisions between different builds.

=== Testing the build

When completed, the local build creates a build directory which contains
a *.tar.gz tarball and an *.xml metadata file. The tarball can be tested using
the Import Plugin function available in the OpenCPN Settings | Plugins page.

=== Local upload and metadata push

After a local, "manual" build the results can be uploaded to Cloudsmith using
the _scripts/local-upload_ script. The scripts needs the configuration from
the configuration file. On linux, the usage is like:

....
$ source ~/.config/local-build.rc
$ scripts/local-upload build
....

This assumes that the _build_ directory is the one used to build. Replace with
actual directory if another location is used.

Windows is similar, here using git-bash:

....
$ source $APPDATA/local-build.rc
$ scripts/local-upload build-windows
....

Likewise, the metadata file in a build directory like 'build' can be pushed
on Linux using:

....
$ ci/git-push build
....

On windows the script must be invoked using `python`.
