== Build Dependencies HOWTO

Before making a local build, build dependencies needs to be installed.
This document tries to describe the procedures.

=== Windows

Before build, run the `buildwin\win_deps.bat` file. The file requires a
working choco installation, see
https://docs.chocolatey.org/en-us/choco/setup[https://docs.chocolatey.org/en-us/choco/setup]

The first run will install various software using choco, and should be
invoked with administrative privileges.

Subsequent builds should still invoke the file, but it can be done with
regular permissions.

A batch file has been found useful for modifying source code with Visual
Studio 2017.

=== Debian/Ubuntu

Install build dependencies using something like:

....
 $ sudo apt install devscripts equivs
 $ sudo mk-build-deps -ir build-deps/control
 $ sudo apt-get -q --allow-unauthenticated install -f
....

=== Flatpak

Install runtime and opencpn as described in flatpak/README.md

=== Android
The templates supports creating tarballs for 32-bit armhf and 64-bit arm64 targets.
Building these requires a local installation of the Android Native Development Kid (NDK)
which can be found at https://developer.android.com/ndk/downloads[].

The build needs to locate the installed NDK. By default, it uses the path _/opt/android/ndk_.
This can be utilized by creating a symlink, something like `sudo ln -s /opt/android/android-ndk-* 
/opt/android/ndk`. As an alternative, the NDK_HOME environment variable can be used. 
It should contain the complete path to the NDK directory.
 
=== MacOS

Use the ci script, which just installs the build deps and configures
when used in a non-CI environment:

....
$ ci/circleci-build-macos
....

After the initial run the build dependencies are in place and
configured. Make for example the tarball using `cd build; make tarball`

xref:Alternative-Workflow.adoc[The Shipdriver Workflow]
