= Overview
:sectnums:

The templates provides functionality for making local builds, continous
integration (CI) builds and optional support for making local builds
which pushes results to CI repositories. 

This page describes the overall process to implement these functions.

== Adapt plugin source to Plugin  Installer.

The plugin must be able to work with the plugin installer which for a
legacy plugin means that the source code needs to be updated.  This is 
described in the xref:ocpn-dev-manual::Plugin-Pi-Adaptation.adoc[Developer
Manual Page].

== Install the templates and enable local builds
Installation of the templates is described in the xref:Plugin-Adaptation.adoc[
Plugin Adaptation Page].

After installing the templates, local builds as described in xref:usage.adoc[
Usage Page] can be done. Such builds generates tarballs which can be tested
using the OpenCPN _Import Plugin_ function.

== Cloud services  configuration

After installing the templates and enabling local builds, next step is to configure
the cloud services. This is described in the xref:InstallConfigure.adoc[
Cloud Services Configuration] Page.  The cloud services includes Cloudsmith,
various builders and the catalog clone on Github.

Cloudsmith is the repository where tarballs are stored. The builders
are used to create these tarballs.

== Integrating with the OpenCPN catalog

Next step is to create a Pull Request against the OpenCPN catalog, thus
making plugin available for end users. Thisis described in the
xref:Metadata-Flow.adoc[Metadata Flow Intro Page] and
xref:InstallConfigure/Catalog-Github-Integration.adoc[Metadata Push Usage Page]

== Extra techniques that may be useful

* Scripts and configuration available in the scripts/ 
directory. This functionality is still experimental. Tentative
documentation is in the xref:Local-ci-build.adoc[Local CI Builds] page.


* xref:Useful-Stuff.adoc[Additional techniques]

xref:index.adoc[<- The ShipDriver template]
