= Overview

== Changes to the plugin

* xref:Plugin-Adaptation.adoc[Adapting the legacy plugin]

Go to this section for a description of the additional files needed to enable the plugin to be compiled and hosted by the cloud services. Also the changes to CMakeLists.txt for the plugin and the changes to the source code.

* xref:InstallConfigure/GitHub.adoc[GitHub]

For this guide the plugin
https://github.com/Rasbats/TideFinder_pi[TideFinder_pi] will be used. Some changes to the settings for the repository on GitHub are needed.

== Cloud Services

Use the links below to see how these services are set up. Probably best to proceed in this order to avoid retracing steps.

* 1. xref:InstallConfigure/Cloudsmith.adoc[Cloudsmith]

This entity hosts the tarballs and metadata files that form the heart of the managed plugin system.

* 2. xref:InstallConfigure/Builders/CircleCI.adoc[CircleCI]

The purpose of the managed system is to produce installers for multiple operating systems. CircleCI hosts virtual machines for a number of OS.

* 3. xref:InstallConfigure/Builders/Appveyor.adoc[Appveyor]

A virtual machine for making Windows OS installers.


* 4. xref:InstallConfigure/Builders/Drone.adoc[Drone]

A virtual machine for the creation of installers for the Raspbian ARMHF system.

* 5. xref:InstallConfigure/Builders/Travis.adoc[Travis]
(May not be needed if Drone is used)

== xref:InstallConfigure/Cloud-Service-Changes.adoc[Cloud service changes]

Environment variables are added to appveyor, circleci and travis.
Changes are needed for the GitHub TideFinder and Plugins repositories.

== First build

After setting up the various cloud service the first build can be made. This results in the tarballs being held in the Cloudsmith repository. 

== Integrating with the OpenCPN catalog

* xref:Metadata-Flow.adoc[Introduction to the metadata flow]
* xref:Catalog-Github-Integration.adoc[Integrating with the catalog using Github]

== Local builds

* xref:Local-Build.adoc[Building locally]
* xref:Usage.adoc[Usage locally]

A local build of the plug can be carried out using the tools described on these pages.

xref:index.adoc[The ShipDriver template]
