= Overview
:sectnums:

The templates provides functionality for making local builds, continous
integration (CI) builds and optional support for making local builds
which pushes results to CI repositories. 

This page describes the overall process to implement these functions.

== Adapt plugin source to Plugin  Installer.

The plugin must be able to work with the plugin installer which for a
legacy plugin means that the source code needs to be updated.  This is 
described in the xref:ocpn-dev-manual::Plugin-Pi-Adaptation.adoc[Developer
Manual Page].

== Install the templates and enable local builds
Installation of the templates is described in the xref:Plugin-Adaptation.adoc[
Plugin Adaptation Page].

After installing the templates, local builds as described in xref:usage.adoc[
Usage Page] can be done. Such builds generates tarballs which can be tested
using the OpenCPN _Import Plugin_ function.

== Cloud services  configuration

After installing the templates and enabling local builds, next step is to configure
the cloud services. This is described in the xref:InstallConfigure.adoc[
Installation and configuration] Page.  The cloud services includes Cloudsmith and
various builders. 

Cloudsmith is the repository where tarballs are stored. The builders
are used to create these tarballs.

== Integrating with the OpenCPN catalog

Next step is to configure the metadata flow. This is the process which makes it
possible for a plugin developer to include and update the plugin in the catalog,
basically to make the plugin available for end users.

The metadata flow is described in the
xref:Metadata-Flow.adoc[metadata flow intro page]

The configuration of this flow is described in  the
xref:InstallConfigure/Catalog-Github-Integration.adoc[
Metadata Push Configuration Page]

== Local builds pushing to Cloudsmith.

This is about scripts and configuration available in the scripts/ 
directory. This functionality is still experimental and not documented.

== Extra techniques that may be useful

xref:Useful-Stuff.adoc[Additional techniques]

xref:index.adoc[<- The ShipDriver template]
