= Adapting the legacy plugin
:sectnums:

== Introduction

In order to enable Continous Integration (CI) a number of template files
and directories needs to be installed in the plugin sources. This page
describes this process.

Before using the shipdriver templates a plugin must as a first step
be adapted to the Plugin Installer as described in the
xref:ocpn-dev-manual::Plugin-Pi-Adaptation.adoc[Developer Manual Page].

== Install template files

=== update-templates

The script _update-templates_  script has been written to simplify the
process of adding the directories/files needed for the workflow.  You will
need git bash for running the script. A guide is included in
xref:UPDATE_TEMPLATES.adoc[UPDATE_TEMPLATES.md].

The script will install all files required in TideFinder except
as noted below.

=== README.md and COPYING

All plugins should have README.md which gives a short summary of the
plugin, links to documentation and, important, an overall copyright
and license statement.  This is a legal requirement to be able to
distribute the plugin

Files in the templates have different licenses, all compatible with
GPL version 3 or later (GPLv3+). If you choose to use this license,
there should also be a file COPYING containing the license.
This could be retrieved using `git checkout shipdriver/master COPYING`


=== CMakeLists.txt

The templates have divided the usual, single CMakeLists.txt into two files
_Plugin.cmake_ and _CMakeLists.txt_. _Plugin.cmake_ contains everything which
is specific for the plugin. _CMakeLists.txt_ is part of the templates and
the same in all plugins.

After running the script, _Plugin.cmake_ is still missing. It can be added
using `git checkout shipdriver/master  Plugin.cmake`

This file needs to be modified, most of the required items will be available
in CMakeLists.txt. After having modified _Plugin.cmake_ to match TideFinder
checkout the generic, template CMakeLists.txt using
`git checkout shipdriver/master CMakeLists.txt`.

This will overwrite the existing _CMakeLists.txt_, but after all it is in the
git history. Commit the two files.

=== The flatpak directory

Start by checking out the shipdriver flatpak directory using:
`git checkout shipdriver/master flatpak`

The directory will contain a file named
_org.opencpn.OpenCPN.Plugin.shipdriver.yaml_.
This should be renamed to match the TideFinder plugin i. e.,
_org.opencpn.OpenCPN.Plugin.TideFinder.yaml_.

After renaming it, edit file and replace ShipDriver with TideFinder in all places.
This is enough for simple plugins.

=== Remove obsolete files

Remove _src/ocpn_plugin.h_ from the source files listed in _Plugin.cmake_. This is now
found in the libs/api-16 directory. The file should also be removed from the src directory.

== Appendix: Affected Files

=== Directories replaced by template files:

[cols="2",width="70%"]
|===
| .circleci | build-deps
| buildwin  | ci
| cmake     | libs
| scripts   | cmake
|===


=== Files added/replaced:

[cols="2",width="70%"]
|===
| .clang-format       | .cmake-format.yaml
| .drone.yml          | .gitattributes
| .gitignore          | .travis.yml
| appveyor.yml        | CMakeLists
| INSTALL.md          | plugin.xml.in
| UPDATE_TEMPLATES.md | update-templates
|===

xref:Overview.adoc[The Shipdriver Workflow]
