= Useful Hints found during compilation

*1. Removing obsolete links from a github repository:*

Note: For Windows Use Git Bash

As an example for removing any tags which include the name `v3':

git push origin –delete $(git tag -l ``*v3*'')

*2. Windows, changing file permissions:*

Using Git Bash…

git update-index –chmod=+x `name-of-shell-script'
(e.g. ./ci/generic-build-raspbian-armhf.sh. wildcards are allowed
e.g. ./ci/*.sh)

git commit -m ``made a file executable''

git push

This is needed when copying files from ./ci/ in ShipDriver to another
plugin that is being upgraded. Windows does not retain the file
permissions for the copied scripts.

*3. Using wxMemoryDC:*

....
`wxMemoryDC mdc(wxNullBitmap);
mdc.SetFont( *pTCFont);

int w, h;
mdc.GetTextExtent(labels, &w, &h);

int label_offset = 10;   

wxBitmap bm(w +  label_offset*2, h + 1);
mdc.SelectObject(bm);
mdc.Clear();

wxPen penText(m_text_color);
mdc.SetPen(penText);

mdc.SetBrush(*wxTRANSPARENT_BRUSH);
mdc.SetTextForeground(m_text_color);
//mdc.SetTextBackground(wxTRANSPARENT);`  ******* Removed this line to get openGL working in otcurrent_pi
....

*4. Empty commit:*

$ git commit --allow-empty -m "Trigger notification"

xref:Overview.adoc[<- Shipdriver template overview]
