= Custom Cloudsmith Repositories

A plugin build usually uploads to cloudsmith repositories. The
repositories used by default are hardcoded on CMakeLists.txt in snippets like

....
set(OCPN_TEST_REPO
    "opencpn/shipdriver-alpha"
    CACHE STRING "Default repository for untagged builds"
)
set(OCPN_BETA_REPO
    "opencpn/shipdriver-beta"
    CACHE STRING
    "Default repository for tagged builds matching 'beta'"
)
set(OCPN_RELEASE_REPO
    "opencpn/shipdriver-prod"
    CACHE STRING
    "Default repository for tagged builds not matching 'beta'"
)
....

When forking a plugin, the developer hasn't permissions to upload to
these hardcoded repositories which belongs to the original owner. To fix
this, other repos could be defined using the environment variables
CLOUDSMITH_UNSTABLE_REPO, CLOUDSMITH_BETA_REPO and
CLOUDSMITH_STABLE_REPO. The values are a complete repo specification
like _alec-leamas/opencpn-plugins-unstable_.

How builder environment variables are set differs for different
providers like circleci, drone.io or appveyor. See 
xref:../InstallConfigure/Builders/IntroCloudServiceChanges.adoc[Cloud service changes]

xref:../InstallConfigure.adoc[<- Installation and configuration]