== Extra techniques that may be useful

xref:Useful-Stuff[Additional techniques]

== Source Code Changes

== Changes associated with API 16

* The plugin api reference is changed from opencpn_plugin_110 to
opencpn_plugin_116

== Change needed for the managed process

* GetPluginDataDir is used instead of *GetpSharedDataLocation()

== Addition for MacOSX

* wxInitAllImageHandlers(): Ensures the png image is recognised on the
Mac

TideFinder_pi::TideFinder_pi(void *ppimgr) :opencpn_plugin_116 (ppimgr)
\{ // Create the PlugIn icons initialize_images();

....
  wxFileName fn;

  auto path = GetPluginDataDir("TideFinder_pi");
  fn.SetPath(path);
  fn.AppendDir("data");
  fn.SetFullName("tidefinder_panel_icon.png");

  path = fn.GetFullPath();

  wxInitAllImageHandlers();

  wxLogDebug(wxString("Using icon path: ") + path);
  if (!wxImage::CanRead(path)) {
      wxLogDebug("Initiating image handlers.");
      wxInitAllImageHandlers();
  }
  wxImage panelIcon(path);
  if (panelIcon.IsOk())
      m_panelBitmap = wxBitmap(panelIcon);
  else
      wxLogWarning("TideFinder panel icon has NOT been loaded");

  m_bShowTideFinder = false;
....

}

*Several source code files are involved in these changes, not just
TideFinder_pi.cpp.*

xref:Alternative-Workflow.adoc[The Alternative Workflow]
