= Builders

All builders needs the environment variables CLOUDSMITH_API_KEY, GIT_REPO
and GIT_KEY_PASSWORD.

In some cases (usually not) also the variables CLOUDSMITH_UNSTABLE_REPO,
CLOUDSMITH_BETA_REPO and CLOUDSMITH_STABLE_REPO are also needed

These variables are documented in the 
xref:InstallConfigure/BuilderEnv.adoc[Builder Environment Page].

---

The following free opensource accounts/services are supported:

* xref:../InstallConfigure/Builders/Appveyor.adoc[Appveyor]

A virtual machine for making Windows OS plugin builds

* xref:../InstallConfigure/Builders/CircleCI.adoc[CircleCI]

CircleCI hosts virtual machines which produce installers for a number of OS

* xref:../InstallConfigure/Builders/Drone.adoc[Drone]

Hosts a virtual machine for the creation of installers for the Raspbian ARMHF system. An alternative to Travis.

* xref:../InstallConfigure/Builders/Travis.adoc[Travis]

A similar machine to Drone for the creation of installers for the Raspbian ARMHF system.

xref:../../InstallConfigure.adoc[<- Installation and configuration]
